### ISSUE TITLE
Tornado ideas

### ISSUE THREAD

**Issue by xXShepardXx** [XuuXiaolan/CodeRebirthReports#2]
Hi, first of all I love your work, secondly I want to ask if it would be possible to: 

1. Make a slider for Tornado pull strength for when you are close / away from it or just a slider in general.
2. An option to make a tornado fly you away at random heights. for example there is a 50% chance you get Yeeted out the map (I loled when it got me haha) and 50% it will fly you away but not as high so it wont be lethal.
3. An option that makes Tornado yell YEEET would be silly af.

Also when you stand still tornado gradually pulls you in, but when you start walking it feels choppy.

**Comment by XuuXiaolan** [comment]
I'll add a slider for strength, I'll make the strength a bit random and I might add a yeet, lol
